### ISSUE TITLE
TypeError: Unexpected keyword argument passed to optimizer: metrics

### ISSUE THREAD

**Issue by Mojahid-Ahmad** [sagar448/Keras-Convolutional-Neural-Network-Python#1]
When I am running  this line
`model.compile(loss='categorical_crossentropy',optimizer=SGD(momentum=0.5, decay=0.0004, metrics=['accuracy']))`
It throws error. I guess it seems related to Version of keras but I am not sure.
Please guide me as I stuck here. Thank you advance

**Comment by sagar448** [comment]
Hello, I am pretty sure it is the version of the Keras. Please downgrade to a version of keras released in 2017, it should work then!

**Comment by Mojahid-Ahmad** [comment]
Actually I found syntax error in code. After correcting the syntax it worked. `model.compile(loss='categorical_crossentropy',optimizer=SGD(momentum=0.5, decay=0.0004, metrics=['accuracy']))`
It Should be
`model.compile(loss='categorical_crossentropy',optimizer=SGD(momentum=0.5, decay=0.0004), metrics=['accuracy'])`
Paranthesiis was missing for SGD()

Thank you Sagar.

**Comment by sagar448** [comment]
@Mojahid-Ahmad  Thanks for pointing that out!
